### ISSUE TITLE
Python2.7 tests fail

### ISSUE THREAD

**Issue by hobarrera** [cocagne/txdbus#46]
Running `tox -e py27` passes, but there's lots of test failures. Looks like the script that runs the tests returns `0`, even if tests failed:

```
$ tox -e py27
GLOB sdist-make: /home/hugo/workspace/Forks/txdbus/setup.py
py27 inst-nodeps: /home/hugo/workspace/Forks/txdbus/.tox/dist/txdbus-1.0.12.zip
py27 installed: appdirs==1.4.3,attrs==17.2.0,Automat==0.6.0,constantly==15.1.0,incremental==17.5.0,packaging==16.8,pyparsing==2.2.0,six==1.10.0,Twisted==17.1.0,txdbus==1.0.12,zope.interface==4.4.1
py27 runtests: PYTHONHASHSEED='61129722'
py27 runtests: commands[0] | python runtests.py
Internal bus tests are currently broken... skipping
.....................................EEEEEEEE.........................EUnhandled error in Deferred:

E..Unhandled Error
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/unix.py", line 193, in doRead
    return self._dataReceived(data)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 119, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_authentication.py", line 387, in dataReceived
    self.gotMessage(line)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_authentication.py", line 531, in recv1
    self.send('AUTH DBUS_COOKIE_SHA1 ' + binascii.hexlify(get_username()))
exceptions.TypeError: b2a_hex() argument 1 must be string or buffer, not None

FE........................................................................................
======================================================================
ERROR: test_launchd_address (txdbus.test.test_endpoints.EndpointsTester)
test_launchd_address
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_endpoints.py", line 13, in setUp
    self.pre_ses = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

======================================================================
ERROR: test_multiple_addresses (txdbus.test.test_endpoints.EndpointsTester)
test_multiple_addresses
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_endpoints.py", line 13, in setUp
    self.pre_ses = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

======================================================================
ERROR: test_no_session (txdbus.test.test_endpoints.EndpointsTester)
test_no_session
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_endpoints.py", line 13, in setUp
    self.pre_ses = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

======================================================================
ERROR: test_nonce_tcp_address (txdbus.test.test_endpoints.EndpointsTester)
test_nonce_tcp_address
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_endpoints.py", line 13, in setUp
    self.pre_ses = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

======================================================================
ERROR: test_session (txdbus.test.test_endpoints.EndpointsTester)
test_session
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_endpoints.py", line 13, in setUp
    self.pre_ses = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

======================================================================
ERROR: test_system (txdbus.test.test_endpoints.EndpointsTester)
test_system
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_endpoints.py", line 13, in setUp
    self.pre_ses = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

======================================================================
ERROR: test_tcp_address (txdbus.test.test_endpoints.EndpointsTester)
test_tcp_address
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_endpoints.py", line 13, in setUp
    self.pre_ses = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

======================================================================
ERROR: test_unix_address (txdbus.test.test_endpoints.EndpointsTester)
test_unix_address
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_endpoints.py", line 13, in setUp
    self.pre_ses = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

======================================================================
ERROR: test_cancel (txdbus.test.test_authentication.ServerObjectTester)
test_cancel
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_authentication.py", line 662, in test_cancel
    return self.conn.test_cancel()
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_authentication.py", line 541, in test_cancel
    self.send('AUTH DBUS_COOKIE_SHA1 '+ binascii.hexlify(get_username()))
TypeError: b2a_hex() argument 1 must be string or buffer, not None

======================================================================
ERROR: test_max_rejects (txdbus.test.test_authentication.ServerObjectTester)
test_max_rejects
----------------------------------------------------------------------
FailTest: Connection unexpectedly dropped

======================================================================
ERROR: test_retry (txdbus.test.test_authentication.ServerObjectTester)
test_retry
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/unix.py", line 193, in doRead
    return self._dataReceived(data)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/hugo/workspace/Forks/txdbus/.tox/py27/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 119, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_authentication.py", line 387, in dataReceived
    self.gotMessage(line)
  File "/home/hugo/workspace/Forks/txdbus/txdbus/test/test_authentication.py", line 531, in recv1
    self.send('AUTH DBUS_COOKIE_SHA1 ' + binascii.hexlify(get_username()))
TypeError: b2a_hex() argument 1 must be string or buffer, not None

======================================================================
FAIL: test_retry (txdbus.test.test_authentication.ServerObjectTester)
test_retry
----------------------------------------------------------------------
FailTest: Connection unexpectedly dropped

----------------------------------------------------------------------
Ran 163 tests in 0.073s

FAILED (failures=1, errors=11)
_____________________________________________________________________________________ summary _____________________________________________________________________________________
  py27: commands succeeded
  congratulations :)

```

Also reproduced [here](https://travis-ci.org/hobarrera/txdbus/jobs/236552195).

**Comment by hobarrera** [comment]
Fixes via #50.
